pull_request_rules:
  #- name: Automatic merge for trusted authors and dependabot
  #  conditions:
  #    - or:
        #  - author=mtdvlpr
        #  - author=sircharlo
  #        - and:
  #            - author=dependabot[bot]
 #             - or:
  #               - title~=^Bump [^\s]+ from ([\d]+)\..+ to \1\.
  #               - title~=^chore\(deps\). bump [^\s]+ from ([\d]+)\..+ to \1\.
  #               - title~=^chore\(deps-dev\). bump [^\s]+ from ([\d]+)\..+ to \1\.
  #  actions:
  #    update:
  #    merge:
 #       method: squash
  - name: Automatically merge Dependabot PRs
    conditions:
      - or:
        - author = dependabot[bot]
        - title ~= chore\(deps
    actions:
      update:
      merge:
        method: rebase
      #queue:

#queue_rules:
  # If you have other queues defined, add this at the end so it is processed last
 # - name: dep-update
   # batch_size: 10
    # Wait for up to 15 minutes for the batch to fill up
  #  batch_max_wait_time: 15 min
  #  queue_conditions:
   #   - author = dependabot[bot]
